version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      type-definitions:
        patterns:
          - "@types/*"
      editor-dependencies:
        patterns:
          - "@codemirror/*"
          - "@uiw/*"
          - markdown-it
          - dompurify
      desktop-dependencies:
        patterns:
          - electron
          - electron-builder
      react-dependencies:
        patterns:
          - react
          - react-dom
          - "@vitejs/*"
          - vite

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
